### ISSUE TITLE
Running the counter examples gives bad wiretype for field, 2 instead of 1

### ISSUE THREAD

**Issue by xmonader** [davebryson/py-abci#13]
Versions: 
```
$ tendermint version
0.15.0
$ abci-cli version
0.9.0
```
Starting the example
```
$ python3 countermint.py
INFO      ABCIServer started on port: 46658
```

Starting tendermint
```
$ tendermint unsafe_reset_all
$ tendermint init            
$ tendermint node            
E[01-23|10:43:58.703] Stopping abci.socketClient for error: proto: bad wiretype for field types.ResponseSetOption.Code: got wiretype 2, want 0 module=abci-client connection=query


E[01-23|10:40:55.782] Stopping abci.socketClient for error: proto: bad wiretype for field types.ResponseSetOption.Code: got wiretype 2, want 0 module=abci-client connection=query

```

**Comment by xmonader** [comment]
I believe it's related to https://github.com/davebryson/py-abci/issues/9 because it works fine with tendermint 0.14 and abci-cli 0.7.1

**Comment by sbellem** [comment]
> I believe it's related to #9 because it works fine with tendermint 0.14 and abci-cli 0.7.1

Yes, that is the same problem I think.

**Comment by davebryson** [comment]
Should be resolved now with the latest merged fixes.  Leaving open for now until more can test

**Comment by xmonader** [comment]
I tried pip install -u and tried manually cloning the repo and still the same 
```
E[01-28|06:38:16.179] Stopping abci.socketClient for error: proto: bad wiretype for field types.ResponseSetOption.Code: got wiretype 2, want 0 module=abci-client connection=query

```

**Comment by davebryson** [comment]
Hmmm.  Sounds like you're not getting the latest version from github.   Try checking out a fresh version then run `pip install`

**Comment by davebryson** [comment]
Should be fixed in the abci-v0.10.0 branch.  Closing for now until we see any more issues
